export {default as AdamFriedman} from './adam-friedman.jpg'
export {default as CeciClark} from './ceci-clark.jpg'
export {default as CourtneyLacy} from './courtney-lacy.jpg'
export {default as JohnCromwell} from './john-cromwell.jpg'
export {default as KirstenPearson} from './kirsten-pearson.jpg'
export {default as MichaelCarter} from './michael-carter.jpg'
