export {default as AdamFriedman} from './adam-friedman.jpg'
export {default as CeciClarke} from './ceci-clarke.jpg'
export {default as CourtneyLacy} from './courtney-lacy.jpg'
export {default as JonCromwell} from './jon-cromwell.jpg'
export {default as KirstenPearson} from './kirsten-pearson.jpg'
export {default as MichaelCarter} from './michael-carter.jpg'
